### ISSUE TITLE
global name 'i' is not defined in Btrfs Subvol handling code

### ISSUE THREAD

**Issue by jmesmon** [funtoo/boot-update#2]
``` shell
nyx@tv /usr/src/linux-3.8.2-gentoo % sudo boot-update

boot-update 1.6.11 /
Copyright 2009-2012 Funtoo Technologies

 [use option "-l" for license info, "-h" for help]

 * Generating config for grub...

Traceback (most recent call last):
  File "/sbin/boot-update", line 233, in <module>
    update(c, ok, allmsgs)
  File "/sbin/boot-update", line 168, in update
    success, msgs = ext.regenerate()[1:]
  File "/usr/lib/python2.7/site-packages/funtoo/boot/extension.py", line 90, in regenerate
    ok, msgs, l = self.generateConfigFile()
  File "/usr/lib/python2.7/site-packages/funtoo/boot/extensions/grub.py", line 211, in generateConfigFile
    ok, msgs, self.defpos, self.defname = self.r.GenerateSections(l, self.generateBootEntry, self.generateOtherBootEntry)
  File "/usr/lib/python2.7/site-packages/funtoo/boot/resolver.py", line 353, in GenerateSections
    ok,  msgs = self. _GenerateLinuxSection(l, sect, sfunc)
  File "/usr/lib/python2.7/site-packages/funtoo/boot/resolver.py", line 283, in _GenerateLinuxSection
    ok, msgs = sfunc(l,sect,kname,kext)
  File "/usr/lib/python2.7/site-packages/funtoo/boot/extensions/grub.py", line 108, in generateBootEntry
    params.append('%sflags=subvol=%s' % i( self.r.rootarg, self.BtrfsSubvol()))
NameError: global name 'i' is not defined
```

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker! :) Follow the action here: https://bugs.funtoo.org/browse/FL-1986

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2038

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
